<script lang="ts">
	import { onMount } from 'svelte';
	import { apiService } from '$lib/services/apiService';
	import {
		aircraft,
		setComponentModel,
		setComponentGenerating,
		setComponentError,
		type ComponentType
	} from '$lib/stores/aircraftStore';
	import type { ComponentType as CT } from '$lib/stores/aircraftStore';
	import type { AeroParameters } from '$lib/types/model';

	// ... existing imports ...
    import { componentMaterials } from '$lib/stores/aircraftStore';
    import { MATERIALS } from '$lib/data/materials';

	export let componentType: CT;

	let prompt = '';
	let previousComponentType: CT = componentType;
	let showSliders = false;

	// Parameter defaults by component type - REAL-LIFE SCALE dimensions
	const defaultParams: Record<CT, AeroParameters> = {
		wings: {
			wingType: 'swept',
			span: 60,
			rootChord: 14,
			tipChord: 3,
			sweepAngle: 30,
			thickness: 12,
			dihedral: 5,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		fuselage: {
			wingType: 'straight',
			span: 0.8,
			rootChord: 60,
			tipChord: 42,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageType: 'commercial',
			fuselageLength: 60,
			fuselageDiameter: 6,
			engineLength: null,
			engineDiameter: null,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0.5,
			positionZ: 0
		},
		engines: {
			wingType: 'straight',
			span: 0.6,
			rootChord: 5,
			tipChord: 2,
			sweepAngle: 0,
			thickness: 90,
			dihedral: 0,
			fuselageLength: null,
			fuselageDiameter: null,
			engineLength: 2.0,
			engineDiameter: 0.5,
			hasVerticalStabilizer: false,
			hasHorizontalStabilizer: false,
			positionX: 0,
			positionY: 0,
			positionZ: 3
		}
	};

	let parameters: AeroParameters = { ...defaultParams[componentType] };
	let lastModelId: string | null = null;

	// Reset parameters when component type changes
	$: if (componentType !== previousComponentType) {
		prompt = '';
		parameters = { ...defaultParams[componentType] };
		showSliders = false;
		lastModelId = null;
		previousComponentType = componentType;

		// Auto-generate default component when switching to a new component type
		if (!$aircraft[componentType]?.model) {
			autoGenerateDefault();
		}
	}

	// Update parameters from generated model only when model changes (not continuously)
	$: if ($aircraft[componentType]?.model?.id && $aircraft[componentType].model.id !== lastModelId) {
		parameters = { ...$aircraft[componentType].model.parameters };
		lastModelId = $aircraft[componentType].model.id;
	}

	$: component = $aircraft[componentType];
	$: isGenerating = component?.isGenerating || false;
	$: error = component?.error || null;
	$: model = component?.model || null;

	async function autoGenerateDefault() {
		console.log('Auto-generating default component:', componentType);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Default component generated:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Auto-generation failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to generate default');
		}
	}

	async function handleUpdateParameters() {
		console.log('Updating parameters:', parameters);
		setComponentGenerating(componentType, true);

		const response = await apiService.updateParameters(parameters);

		if (response.success && response.model) {
			console.log('Parameters updated successfully:', response.model.name);
			setComponentModel(componentType, response.model);
		} else {
			console.error('Update failed:', response.error);
			setComponentError(componentType, response.error || 'Failed to update');
		}
	}

	$: currentMaterialId = $componentMaterials[componentType];
    $: currentMaterial = MATERIALS.find(m => m.id === currentMaterialId) || MATERIALS[0];
    
    // Calculate weight based on Backend Volume * Material Density
    // Model volume is in m³, Density in kg/m³
    $: volume = model?.metadata?.volume || 0; 
	const STRUCTURAL_FILL_FACTOR = 0.25; 

// ... inside the component
$: currentMaterialId = $componentMaterials[componentType];
$: currentMaterial = MATERIALS.find(m => m.id === currentMaterialId) || MATERIALS[0];

// Get raw volume
$: rawVolume = model?.metadata?.volume || 0;

// Apply the factor to get "Effective Volume"
$: effectiveVolume = rawVolume * STRUCTURAL_FILL_FACTOR;

// Calculate final weight
$: weight = effectiveVolume * currentMaterial.density;
    
    function handleMaterialChange(event: Event) {
        const select = event.target as HTMLSelectElement;
        $componentMaterials[componentType] = select.value;
    }

	 onMount(() => {
        // If the component has a model, but the volume is 0 or missing (e.g., after backend restart),
        // we force a quiet update to run the new backend math and get the volume.
        if (model && (!model.metadata?.volume || model.metadata.volume === 0)) {
            console.log("Model exists but volume is missing. Auto-updating to calculate physics...");
            handleUpdateParameters();
        }
    });
</script>

<div class="component-editor">
	{#if error}
		<div class="error-panel">
			<svg viewBox="0 0 16 16" fill="none">
				<circle cx="8" cy="8" r="7" stroke="currentColor" stroke-width="1.5"/>
				<path d="M8 4V8M8 10.5V11" stroke="currentColor" stroke-width="2" stroke-linecap="square"/>
			</svg>
			<div class="error-content">
				<span class="error-label">ERROR</span>
				<p>{error}</p>
			</div>
		</div>
	{/if}

	{#if isGenerating}
		<div class="generating-panel">
			<div class="generating-spinner"></div>
			<div class="generating-content">
				<span class="generating-label">PROCESSING</span>
				<p>Generating {componentType.replace('_', ' ')}...</p>
			</div>
		</div>
	{/if}

	 <!-- NEW: Materials & Physics Section (Insert before or after controls-section) -->
    <div class="controls-section">
        <div class="section-title">
            <svg viewBox="0 0 16 16" fill="none">
                <path d="M8 2L14 5L8 8L2 5L8 2Z" stroke="currentColor" stroke-width="1.5"/>
                <path d="M2 11L8 14L14 11" stroke="currentColor" stroke-width="1.5"/>
                <path d="M2 8L8 11L14 8" stroke="currentColor" stroke-width="1.5"/>
            </svg>
            <span>MATERIALS & PHYSICS</span>
        </div>

        <div class="control-group">
            <div class="group-label">STRUCTURAL COMPOSITION</div>

            <!-- Material Selector -->
            <div class="param-control">
                <div class="param-header">
                    <label class="param-label">MATERIAL SYSTEM</label>
                    <span class="param-code">MAT-SYS</span>
                </div>
                <select 
                    value={currentMaterialId} 
                    on:change={handleMaterialChange}
                    disabled={isGenerating} 
                    class="param-select"
                >
                    {#each MATERIALS as mat}
                        <option value={mat.id}>{mat.name}</option>
                    {/each}
                </select>
                
                <!-- Tech Specs Grid (Replaces the simple list) -->
                <div class="specs-grid">
                    <div class="spec-item">
                        <span class="label">DENSITY</span>
                        <span class="val">{currentMaterial.density} <span class="unit">kg/m³</span></span>
                    </div>
                    <div class="spec-item">
                        <span class="label">YIELD STR</span>
                        <span class="val">{currentMaterial.yieldStrength} <span class="unit">MPa</span></span>
                    </div>
                </div>
            </div>

            <!-- Transparent Calculation Box (Replaces simple weight bar) -->
            <div class="calculation-box">
                <div class="calc-header">MASS CALCULATION PROTOCOL</div>
                
                <!-- Row 1: Raw Geometry -->
                <div class="calc-row">
                    <span>RAW VOL (GEOMETRY)</span>
                    <span class="calc-val">{rawVolume.toFixed(2)} m³</span>
                </div>

                <!-- Row 2: The Engineering Factor -->
                <div class="calc-row factor">
                    <span>× STRUCTURAL FILL</span>
                    <span class="calc-val">{(STRUCTURAL_FILL_FACTOR * 100)}%</span>
                </div>
                <div class="calc-note">Account for hollow structure (Ribs/Spars)</div>

                <!-- Row 3: Material -->
                <div class="calc-row">
                    <span>× MATERIAL DENSITY</span>
                    <span class="calc-val">{currentMaterial.density} kg/m³</span>
                </div>

                <div class="calc-divider"></div>

                <!-- Final Result -->
                <div class="calc-result">
                    <span>TOTAL EST. WEIGHT</span>
                    <span class="final-weight">
                        {weight > 0 ? weight.toFixed(1) : '---'} <span class="unit">kg</span>
                    </span>
                </div>
            </div>
        </div>
    </div>

	<!-- Parameter Controls -->
	<div class="controls-section">
		<div class="section-title">
			<svg viewBox="0 0 16 16" fill="none">
				<rect x="2" y="6" width="4" height="8" stroke="currentColor" stroke-width="1.5"/>
				<rect x="7" y="2" width="4" height="12" stroke="currentColor" stroke-width="1.5"/>
				<rect x="12" y="4" width="4" height="10" stroke="currentColor" stroke-width="1.5"/>
			</svg>
			<span>PARAMETER CONTROLS</span>
		</div>

		{#if componentType === 'wings'}
			<!-- Wing Configuration -->
			<div class="control-group">
				<div class="group-label">WING CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TYPE</label>
						<span class="param-code">WT-01</span>
					</div>
					<select bind:value={parameters.wingType} on:change={handleUpdateParameters} disabled={isGenerating} class="param-select">
						<option value="delta">DELTA</option>
						<option value="swept">SWEPT</option>
						<option value="straight">STRAIGHT</option>
						<option value="tapered">TAPERED</option>
					</select>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">SPAN</label>
						<div class="param-value-display">
							<span class="value">{parameters.span.toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="10"
							max="90"
							step="0.5"
							bind:value={parameters.span}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">10m</span>
							<span class="mark">50m</span>
							<span class="mark">90m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">ROOT CHORD</label>
						<div class="param-value-display">
							<span class="value">{parameters.rootChord.toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="3"
							max="20"
							step="0.5"
							bind:value={parameters.rootChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">3m</span>
							<span class="mark">11m</span>
							<span class="mark">20m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TIP CHORD</label>
						<div class="param-value-display">
							<span class="value">{(parameters.tipChord || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="1"
							max="6"
							step="0.2"
							bind:value={parameters.tipChord}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">1m</span>
							<span class="mark">3.5m</span>
							<span class="mark">6m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">SWEEP ANGLE</label>
						<div class="param-value-display">
							<span class="value">{parameters.sweepAngle.toFixed(0)}</span>
							<span class="unit">deg</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0"
							max="90"
							step="5"
							bind:value={parameters.sweepAngle}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0</span>
							<span class="mark">45</span>
							<span class="mark">90</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">THICKNESS</label>
						<div class="param-value-display">
							<span class="value">{parameters.thickness.toFixed(0)}</span>
							<span class="unit">%</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="8"
							max="20"
							step="1"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">8</span>
							<span class="mark">14</span>
							<span class="mark">20</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIHEDRAL</label>
						<div class="param-value-display">
							<span class="value">{parameters.dihedral.toFixed(0)}</span>
							<span class="unit">deg</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="-15"
							max="15"
							step="1"
							bind:value={parameters.dihedral}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">-15</span>
							<span class="mark">0</span>
							<span class="mark">15</span>
						</div>
					</div>
				</div>
			</div>

		{/if}

		{#if componentType === 'fuselage'}
			<div class="control-group">
				<div class="group-label">FUSELAGE CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">TYPE</label>
						<span class="param-code">FS-01</span>
					</div>
					<select
						bind:value={parameters.fuselageType}
						on:change={handleUpdateParameters}
						disabled={isGenerating}
						class="param-select"
					>
						<option value="commercial">COMMERCIAL</option>
						<option value="fighter">FIGHTER JET</option>
						<option value="cargo">CARGO</option>
						<option value="private">PRIVATE</option>
					</select>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">LENGTH</label>
						<div class="param-value-display">
							<span class="value">{(parameters.fuselageLength || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="12"
							max="85"
							step="1"
							bind:value={parameters.fuselageLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">12m</span>
							<span class="mark">48m</span>
							<span class="mark">85m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIAMETER</label>
						<div class="param-value-display">
							<span class="value">{(parameters.fuselageDiameter || 0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="1.5"
							max="8"
							step="0.2"
							bind:value={parameters.fuselageDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">1.5m</span>
							<span class="mark">4.75m</span>
							<span class="mark">8m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">THICKNESS</label>
						<div class="param-value-display">
							<span class="value">{parameters.thickness.toFixed(0)}</span>
							<span class="unit">%</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="70"
							max="100"
							step="5"
							bind:value={parameters.thickness}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">70</span>
							<span class="mark">85</span>
							<span class="mark">100</span>
						</div>
					</div>
				</div>
			</div>
		{/if}

		{#if componentType === 'engines'}
			<div class="control-group">
				<div class="group-label">ENGINE CONFIGURATION</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">LENGTH</label>
						<div class="param-value-display">
							<span class="value">{(parameters.engineLength || 2.0).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="2"
							max="6"
							step="0.2"
							bind:value={parameters.engineLength}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">2m</span>
							<span class="mark">4m</span>
							<span class="mark">6m</span>
						</div>
					</div>
				</div>

				<div class="param-control">
					<div class="param-header">
						<label class="param-label">DIAMETER</label>
						<div class="param-value-display">
							<span class="value">{(parameters.engineDiameter || 0.5).toFixed(2)}</span>
							<span class="unit">m</span>
						</div>
					</div>
					<div class="param-slider-container">
						<input
							type="range"
							min="0.5"
							max="3.5"
							step="0.1"
							bind:value={parameters.engineDiameter}
							on:change={handleUpdateParameters}
							disabled={isGenerating}
							class="param-slider"
						/>
						<div class="slider-marks">
							<span class="mark">0.5m</span>
							<span class="mark">2m</span>
							<span class="mark">3.5m</span>
						</div>
					</div>
				</div>
			</div>
		{/if}
	</div>
</div>

<style>
	.component-editor {
		display: flex;
		flex-direction: column;
		gap: var(--space-5);
	}

	/* ERROR PANEL */
	.error-panel {
		display: flex;
		gap: var(--space-3);
		padding: var(--space-4);
		background: rgba(239, 83, 80, 0.1);
		border: 1px solid var(--red-error);
		border-left: 3px solid var(--red-error);
	}

	.error-panel svg {
		width: 20px;
		height: 20px;
		color: var(--red-error);
		flex-shrink: 0;
	}

	.error-content {
		flex: 1;
	}

	.error-label {
		display: block;
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--red-error);
		margin-bottom: var(--space-1);
	}

	.error-content p {
		font-size: 0.8125rem;
		color: var(--gray-200);
		margin: 0;
		line-height: 1.4;
	}

	/* GENERATING PANEL */
	.generating-panel {
		display: flex;
		gap: var(--space-3);
		padding: var(--space-4);
		background: rgba(255, 167, 38, 0.1);
		border: 1px solid var(--amber-warning);
		border-left: 3px solid var(--amber-warning);
	}

	.generating-spinner {
		width: 20px;
		height: 20px;
		border: 2px solid var(--amber-warning);
		border-top-color: transparent;
		border-radius: 50%;
		animation: spin 0.8s linear infinite;
		flex-shrink: 0;
	}

	@keyframes spin {
		to { transform: rotate(360deg); }
	}

	.generating-content {
		flex: 1;
	}

	.generating-label {
		display: block;
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--amber-warning);
		margin-bottom: var(--space-1);
	}

	.generating-content p {
		font-size: 0.8125rem;
		color: var(--gray-200);
		margin: 0;
		text-transform: capitalize;
	}

	/* CONTROLS SECTION */
	.controls-section {
		display: flex;
		flex-direction: column;
		gap: var(--space-5);
	}

	.section-title {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		padding-bottom: var(--space-3);
		border-bottom: 1px solid var(--border-subtle);
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--gray-400);
	}

	.section-title svg {
		width: 14px;
		height: 14px;
		color: var(--cyan-500);
	}

	/* CONTROL GROUP */
	.control-group {
		display: flex;
		flex-direction: column;
		gap: var(--space-4);
		padding: var(--space-4);
		background: var(--blueprint-surface);
		border: 1px solid var(--border-subtle);
	}

	.group-label {
		font-size: 0.5625rem;
		font-weight: 700;
		letter-spacing: 0.15em;
		color: var(--cyan-400);
		padding-bottom: var(--space-2);
		border-bottom: 1px solid var(--border-subtle);
	}

	/* PARAMETER CONTROLS */
	.param-control {
		display: flex;
		flex-direction: column;
		gap: var(--space-2);
	}

	.param-header {
		display: flex;
		justify-content: space-between;
		align-items: center;
	}

	.param-label {
		font-size: 0.625rem;
		font-weight: 700;
		letter-spacing: 0.1em;
		color: var(--gray-300);
	}

	.param-code {
		font-family: var(--font-technical);
		font-size: 0.5625rem;
		font-weight: 700;
		letter-spacing: 0.05em;
		color: var(--gray-500);
	}

	.param-value-display {
		display: flex;
		align-items: baseline;
		gap: var(--space-1);
		font-family: var(--font-technical);
	}

	.param-value-display .value {
		font-size: 0.875rem;
		font-weight: 600;
		color: var(--cyan-400);
	}

	.param-value-display .unit {
		font-size: 0.625rem;
		color: var(--gray-500);
	}

	/* SELECT */
	.param-select {
		padding: var(--space-2) var(--space-3);
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		color: var(--gray-100);
		font-size: 0.75rem;
		font-weight: 600;
		cursor: pointer;
		transition: all 0.2s;
	}

	.param-select:hover:not(:disabled) {
		border-color: var(--cyan-600);
	}

	.param-select:focus {
		outline: none;
		border-color: var(--cyan-500);
		box-shadow: 0 0 10px var(--cyan-glow);
	}

	.param-select:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	/* SLIDER */
	.param-slider-container {
		display: flex;
		flex-direction: column;
		gap: var(--space-1);
	}

	.param-slider {
		-webkit-appearance: none;
		appearance: none;
		width: 100%;
		height: 4px;
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		border-radius: 2px;
		outline: none;
		cursor: pointer;
		position: relative;
	}

	.param-slider::-webkit-slider-thumb {
		-webkit-appearance: none;
		appearance: none;
		width: 16px;
		height: 16px;
		background: var(--cyan-500);
		border: 2px solid var(--blueprint-bg);
		border-radius: 2px;
		cursor: pointer;
		box-shadow: 0 0 10px var(--cyan-glow);
		transition: all 0.2s;
	}

	.param-slider::-webkit-slider-thumb:hover {
		background: var(--cyan-400);
		transform: scale(1.1);
		box-shadow: 0 0 15px var(--cyan-glow);
	}

	.param-slider::-moz-range-thumb {
		width: 16px;
		height: 16px;
		background: var(--cyan-500);
		border: 2px solid var(--blueprint-bg);
		border-radius: 2px;
		cursor: pointer;
		box-shadow: 0 0 10px var(--cyan-glow);
		transition: all 0.2s;
	}

	.param-slider::-moz-range-thumb:hover {
		background: var(--cyan-400);
		transform: scale(1.1);
		box-shadow: 0 0 15px var(--cyan-glow);
	}

	.param-slider:disabled {
		opacity: 0.5;
		cursor: not-allowed;
	}

	.slider-marks {
		display: flex;
		justify-content: space-between;
		padding: 0 var(--space-1);
	}

	.mark {
		font-family: var(--font-technical);
		font-size: 0.5625rem;
		color: var(--gray-500);
	}

	/* CHECKBOX */
	.checkbox-control {
		display: flex;
		align-items: center;
		gap: var(--space-3);
		padding: var(--space-3);
		background: var(--blueprint-bg);
		border: 1px solid var(--border-subtle);
		cursor: pointer;
		transition: all 0.2s;
	}

	.checkbox-control:hover:not(:has(input:disabled)) {
		border-color: var(--cyan-600);
		background: rgba(3, 169, 244, 0.05);
	}

	.checkbox-control input[type='checkbox'] {
		width: 18px;
		height: 18px;
		margin: 0;
		cursor: pointer;
		accent-color: var(--cyan-500);
		flex-shrink: 0;
	}

	.checkbox-control input[type='checkbox']:disabled {
		cursor: not-allowed;
		opacity: 0.5;
	}

	.checkbox-label {
		display: flex;
		align-items: center;
		gap: var(--space-2);
		font-size: 0.6875rem;
		font-weight: 600;
		letter-spacing: 0.05em;
		color: var(--gray-300);
	}

	.check-icon {
		width: 12px;
		height: 12px;
		color: var(--cyan-500);
	}

	    /* New Material Styles */
    .material-info {
        margin-top: var(--space-2);
        padding: var(--space-2);
        background: rgba(3, 169, 244, 0.05);
        border: 1px solid var(--border-subtle);
        font-family: var(--font-technical);
        font-size: 0.625rem;
    }

    .info-row {
        display: flex;
        justify-content: space-between;
        color: var(--gray-400);
        margin-bottom: 2px;
    }

    .info-row .value {
        color: var(--cyan-300);
    }

    .weight-bar {
        height: 4px;
        background: var(--blueprint-bg);
        border: 1px solid var(--border-subtle);
        margin-top: var(--space-1);
        border-radius: 2px;
        overflow: hidden;
    }

    .bar-fill {
        height: 100%;
        background: linear-gradient(90deg, var(--cyan-600), var(--cyan-400));
    }

    .description-text {
        font-size: 0.625rem;
        color: var(--gray-500);
        font-style: italic;
        margin-top: var(--space-1);
    }

	.specs-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: var(--space-2);
        margin-top: var(--space-2);
    }

    .spec-item {
        background: rgba(3, 169, 244, 0.05);
        border: 1px solid var(--border-subtle);
        padding: var(--space-2);
        display: flex;
        flex-direction: column;
        gap: 2px;
    }

    .spec-item .label {
        font-size: 0.5rem;
        color: var(--gray-500);
        letter-spacing: 0.05em;
    }

    .spec-item .val {
        font-family: var(--font-technical);
        font-size: 0.75rem;
        color: var(--cyan-300);
    }

    /* Calculation Box Styles */
    .calculation-box {
        margin-top: var(--space-4);
        padding: var(--space-3);
        background: var(--blueprint-bg);
        border: 1px dashed var(--gray-600); /* Dashed line implies "Analysis" */
    }

    .calc-header {
        font-size: 0.5625rem;
        font-weight: 700;
        color: var(--gray-500);
        margin-bottom: var(--space-2);
        letter-spacing: 0.1em;
        text-transform: uppercase;
    }

    .calc-row {
        display: flex;
        justify-content: space-between;
        font-size: 0.6875rem;
        color: var(--gray-400);
        margin-bottom: 4px;
        font-family: var(--font-technical);
    }

    .calc-row.factor {
        color: var(--cyan-400); /* Highlight the factor */
    }

    .calc-val {
        color: var(--gray-200);
    }

    .calc-note {
        font-size: 0.5rem;
        color: var(--gray-600);
        text-align: right;
        margin-bottom: var(--space-2);
        font-style: italic;
    }

    .calc-divider {
        height: 1px;
        background: var(--gray-600);
        margin: var(--space-2) 0;
    }

    .calc-result {
        display: flex;
        justify-content: space-between;
        align-items: center;
    }

    .calc-result span:first-child {
        font-size: 0.625rem;
        font-weight: 700;
        letter-spacing: 0.1em;
        color: var(--gray-300);
    }

    .final-weight {
        font-family: var(--font-technical);
        font-size: 1.125rem;
        font-weight: 700;
        color: var(--cyan-400);
        text-shadow: 0 0 10px rgba(41, 182, 246, 0.3);
    }
</style>
